require('capslock.telescope')
require('capslock.cmp')
require('capslock.lsp')
require('capslock.nvimtree')
require('capslock.bufferline')
require('capslock.treesitter')
require('capslock.autopairs')
require("capslock.toggleterm")
