require("plugins.treesitter")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.autopairs")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.toggleterm")
